IncomeExpenseAppCoreMVC/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IncomeExpenseAppCoreMVC.Manager;
using IncomeExpenseAppCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace IncomeExpenseAppCoreMVC.Controllers
{
    public class ExpenseController : Controller
    {
        private ExpenseManager expenseManager;
        private BankInfoManager bankInfoManager;
        public ExpenseController()
        {
            expenseManager = new ExpenseManager();
            bankInfoManager=new BankInfoManager();
        }
        [HttpGet]
        public IActionResult Save()
        {
            ViewBag.BankList = bankInfoManager.ListOfBank();
            return View();
        }
        [HttpPost]
        public IActionResult Save(Expense expense)
        {
            expense.ApproveStatus = "No";
            string message = expenseManager.Save(expense);
            ViewBag.Message = message;
            ViewBag.BankList = bankInfoManager.ListOfBank();
            return View();
        }


        [HttpGet]
        public IActionResult ExpensePendingList()
        {
            List<Expense> pendingList = expenseManager.PendingList();
            ViewBag.PendingList = pendingList;
            // return View(pendingList);
            return View();
        }

        public JsonResult Approve(string[] values)
        {
            List<Expense> expenses = new List<Expense>();
            foreach (var id in values)
            {
                Expense expense = new Expense();
                expense.Id = Convert.ToInt32(id);
                expenses.Add(expense);
            }

            string message = expenseManager.UpdateApproveStatus(expenses);
            return Json(message);
        }

        //for junior
        [HttpGet]
        public IActionResult ViewPendingList()
        {
            List<Expense> pendingList = expenseManager.PendingList();
            ViewBag.PendingList = pendingList;
            return View();
        }

        [HttpGet]
        public IActionResult MonthlyExpense()
        {
            ViewBag.YearList = expenseManager.GetYearList();
            return View();
        }

        [HttpPost]
        public IActionResult MonthlyExpense(string month, string year)
        {
            List<Expense> monthlyReport = expenseManager.MonthlyIncome(month, year);
            decimal totalExpense = CalculateAmount.Calculate(monthlyReport);
            ViewBag.TotalExpense = totalExpense;
            ViewBag.MonthlyReport = monthlyReport;
            ViewBag.YearList = expenseManager.GetYearList();
            return View();
        }

        //for Junior
        [HttpGet]
        public IActionResult ViewMonthlyExpense()
        {
            ViewBag.YearList = expenseManager.GetYearList();
            return View();
        }

        [HttpPost]
        public IActionResult ViewMonthlyExpense(string month, string year)
        {
            List<Expense> monthlyReport = expenseManager.MonthlyIncome(month, year);
            decimal totalExpense = CalculateAmount.Calculate(monthlyReport);
            ViewBag.TotalExpense = totalExpense;
            ViewBag.MonthlyReport = monthlyReport;
            ViewBag.YearList = expenseManager.GetYearList();
            return View();
        }
    }
}

IncomeExpenseAppCoreMVC/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using IncomeExpenseAppCoreMVC.Manager;
using IncomeExpenseAppCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace IncomeExpenseAppCoreMVC.Controllers
{
    public class LoginController : Controller
    {

        [HttpGet]
        public IActionResult LoginToFrom()
        {
            return View();
        }
        [HttpPost]
        public IActionResult LoginToFrom(Login login)
        {
            LoginManager loginManage = new LoginManager();
            Login loginInfo = loginManage.LoginInfo(login);
            ViewBag.LoginInfo = loginInfo;
            if (loginInfo.Designation == null)
            {
                ViewBag.Message = "Not match email or password";
                return View();
            }
            else if (loginInfo.Designation == "Jr Accountant")
            {
                return RedirectToAction("Save", "income");
            }
            else if(loginInfo.Designation=="Sr Accountant")
            {
                return RedirectToAction("PendingList", "Income");
            }
            return View();
        }
    }
}

IncomeExpenseAppCoreMVC/Controllers/YearlyReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IncomeExpenseAppCoreMVC.Manager;
using IncomeExpenseAppCoreMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace IncomeExpenseAppCoreMVC.Controllers
{
    public class YearlyReportController : Controller
    {
        private YearlyReportManager yearlyReportManager;   
        public YearlyReportController()
        {
            yearlyReportManager=new YearlyReportManager();
        }
       
        [HttpGet]
        public IActionResult YearlyReport()
        {
           List<string>yearList= yearlyReportManager.GetYearList();
           ViewBag.YearList = yearList;
            return View();
        }
        [HttpPost]
        public IActionResult YearlyReport(string year)
        {
            decimal income = 0;
            decimal expense = 0;
            decimal yearlyIncome = 0;
            decimal yearlyExpense = 0;
            decimal januaryExpense = 0;
            decimal februaryExpense = 0;
            decimal marchExpense = 0;
            decimal aprilExpense = 0;
            decimal mayExpense = 0;
            decimal juneExpense = 0;
            decimal julyExpense = 0;
            decimal augustExpense = 0;
            decimal septemberExpense = 0;
            decimal octoberExpense = 0;
            decimal novemberExpense = 0;
            decimal decemberExpense = 0;
            decimal januaryIncome = 0;
            decimal februaryIncome = 0;
            decimal marchIncome = 0;
            decimal aprilIncome = 0;
            decimal mayIncome = 0;
            decimal juneIncome = 0;
            decimal julyIncome = 0;
            decimal augustIncome = 0;
            decimal septemberIncome = 0;
            decimal octoberIncome = 0;
            decimal novemberIncome = 0;
            decimal decemberIncome = 0;

            for (int i = 1; i <= 12; i++)
            {
                if (i == 1)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("1", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.JanuaryIncome = totalmonthlyIncome;
                    januaryIncome = totalmonthlyIncome;
                }
                else if (i == 2)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("2", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.FebruaryIncome = totalmonthlyIncome;
                    februaryIncome = totalmonthlyIncome;
                }
                else if (i == 3)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("3", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.MarchIncome = totalmonthlyIncome;
                    marchIncome = totalmonthlyIncome;
                }
                else if (i == 4)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("4", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.AprilIncome = totalmonthlyIncome;
                    aprilIncome = totalmonthlyIncome;
                }
                else if (i == 5)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("5", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.MayIncome = totalmonthlyIncome;
                    mayIncome = totalmonthlyIncome;
                }
                else if (i == 6)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("6", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.JuneIncome = totalmonthlyIncome;
                    juneIncome = totalmonthlyIncome;
                }
                else if (i == 7)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("7", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.JulyIncome = totalmonthlyIncome;
                    juneIncome = totalmonthlyIncome;
                }
                else if (i == 8)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("8", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.AugustIncome = totalmonthlyIncome;
                    augustIncome = totalmonthlyIncome;
                }
                else if (i == 9)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("9", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.SeptemberIncome = totalmonthlyIncome;
                    septemberIncome = totalmonthlyIncome;
                }
                else if (i == 10)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("10", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.OctoberIncome = totalmonthlyIncome;
                    octoberIncome = totalmonthlyIncome;
                }
                else if (i == 11)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("11", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.NovemberIncome = totalmonthlyIncome;
                    novemberIncome = totalmonthlyIncome;
                }
                else if (i == 12)
                {
                    List<Income> incomes = yearlyReportManager.MonthlyIncome("12", year);
                    decimal totalmonthlyIncome = CalculateAmount.Calculate(incomes);
                    yearlyIncome += totalmonthlyIncome;
                    ViewBag.DecemberIncome = totalmonthlyIncome;
                    decemberIncome = totalmonthlyIncome;
                }
            }

            for (int i = 1; i <= 12; i++)
            {
                if (i == 1)
                {
                    List<Expense> expenses = yearlyReportManager.MonthlyExpense("1", year);
                    decimal totalMonthlyExpense = CalculateAmount.Calculate(expenses);
                    yearlyExpense += totalMonthlyExpense;
                    ViewBag.JanuaryExpense = totalMonthlyExpense;
                    januaryExpense = totalMonthlyExpense;
                }
                else if (i == 2)
                {
                    List<Expense> expenses = yearlyReportManager.MonthlyExpense("2", year);
                    decimal totalMonthlyExpense = CalculateAmount.Calculate(expenses);
                    yearlyExpense += totalMonthlyExpense;
                    ViewBag.FebruaryExpense = totalMonthlyExpense;
                    februaryExpense = totalMonthlyExpense;
                }
                else if (i == 3)
                {
                    List<Expense> expenses = yearlyReportManager.MonthlyExpense("3", year);
                    decimal totalMonthlyExpense = CalculateAmount.Calculate(expenses);
                    yearlyExpense += totalMonthlyExpense;
                    ViewBag.MarchExpense = totalMonthlyExpense;
                    marchExpense = totalMonthlyExpense;
                }
                else if (i == 4)
                {
                    List<Expense> expenses = yearlyReportManager.MonthlyExpense("4", year);
                    decimal totalMonthlyExpense = CalculateAmount.Calculate(expenses);
                    yearlyExpense += totalMonthlyExpense;
                    ViewBag.AprilExpense = totalMonthlyExpense;
                    aprilExpense = totalMonthlyExpense;
                }
                else if (i == 5)
                {
                    List<Expense> expenses = yearlyReportManager.MonthlyExpense("5", year);
                    decimal totalMonthlyExpense = CalculateAmount.Calculate(expenses);
                    yearlyExpense += totalMonthlyExpense;
                    ViewBag.MayExpense = totalMonthlyExpense;
                    mayExpense = totalMonthlyExpense;
                }
                else if (i == 6)
                {
                    List<Expense> expenses = yearlyReportManager.MonthlyExpense("6", year);
                    decimal totalMonthlyExpense = CalculateAmount.Calculate(expenses);
                    yearlyExpense += totalMonthlyExpense;
                    ViewBag.JuneExpense = totalMonthlyExpense;
                    julyExpense = totalMonthlyExpense;
                }
                else if (i == 7)
                {
                    List<Expense> expenses = yearlyReportManager.MonthlyExpense("7", year);
                    decimal totalMonthlyExpense = CalculateAmount.Calculate(expenses);
                    yearlyExpense += totalMonthlyExpense;
                    ViewBag.JulyExpense = totalMonthlyExpense;
                    julyExpense = totalMonthlyExpense;
                }

IncomeExpenseAppCoreMVC/Views/Shared/LayoutForAnother.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>@ViewData["Title"] - IncomeExpenseAppCoreMVC</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">Entry<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Income" asp-action="Save" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">Income Entry</a></li>
                            <li><a asp-area="" asp-controller="Expense" asp-action="Save" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">Expense Entry</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">PendingList<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Income" asp-action="ViewPendingList" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">View Income List</a></li>
                            <li><a asp-area="" asp-controller="Expense" asp-action="ViewPendingList" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">View Expense List</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">MonthlyReport<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Income" asp-action="ViewMonthlyIncome" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif"> Income Report</a></li>
                            <li><a asp-area="" asp-controller="Expense" asp-action="ViewMonthlyExpense" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif"> Expense Report</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Login" asp-action="LoginToFrom" style="font-size:160%;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;font-style:italic">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

        <partial name="_CookieConsentPartial" />
        <div class="container body-content">
            @RenderBody()

            <footer></footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"></script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>
        @RenderSection("Scripts", required: false)
</body>
</html>

IncomeExpenseAppCoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IncomeExpenseAppCoreMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">PendingList<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Income" asp-action="PendingList" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">View Income List</a></li>
                            <li><a asp-area="" asp-controller="Expense" asp-action="ExpensePendingList" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">View Expense List</a></li>
                        </ul>
                    </li>


                    
                </ul>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">MonthlyReport<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Income" asp-action="MonthlyIncome" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif"> Income Report</a></li>
                            <li><a asp-area="" asp-controller="Expense" asp-action="MonthlyExpense" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif"> Expense Report</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    
                    <li><a asp-area="" asp-controller="YearlyReport" asp-action="YearlyReport" style="font-size:large;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif">YearlyReport</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Login" asp-action="LoginToFrom" style="font-size:160%;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;font-style:italic">Logout</a></li>
                </ul>
               
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    <div class="container body-content">
        @RenderBody()

        <footer></footer>
    </div>



    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>